#!/bin/bash
#=============================================================#
# Script Name:    Who                                         #                                                                        #
# By:             Reed Resch                                  #                                                                     #      
# Date:           4/19/2021                                   #                                                                        #
# Purpose:        View Logged on Users                        #                                                             #
#                                                             #                                                                                                          #
#=============================================================#
Logged_on_users=$ who | cut -d' ' -f1 | sort | uniq
